name: Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: bot-axl
        password: ${{ secrets.GH_TOKEN }}


    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/accelnomics-technologies/solr:${{ github.sha }}

  update-manifests:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout manifests repository
      uses: actions/checkout@v2
      with:
        repository: accelnomics-technologies/argocd-manifests
        token: ${{ secrets.GH_TOKEN }}

        path: eml-manifests

    

    - name: Configure Git
      run: |
        git config --global user.email "axlbot@accelnomics.com"
        git config --global user.name "bot-axl"

    

    - name: Update Deployment File
      run: |
        
        cd argocd-manifests/solr_manifests

        # Update image tag in deployment.yaml using sed
        sed -i "s|image: ghcr.io/accelnomics-technologies/solr:.*|image: ghcr.io/accelnomics-technologies/solr:${{ github.sha }}|" deployment.yaml

        # Stage and commit the updated deployment.yaml
        git add deployment.yaml
        git commit -m "Update image tag to ${IMAGE_TAG} in deployment.yaml"

    - name: Push changes to repository
      run: |
        cd argocd-manifests/solr_manifests
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
